# 服务名称
spring:
  application:
    name: micro-job-node
  #数据源配置信息
  datasource:
    druid:
      url: jdbc:mysql://xxx.xxx.xxx:3306/job?characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xxxx
      password: xxxx
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1 from dual
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 1
      max-pool-prepared-statement-per-connection-size: 20
      #打开PSCache，并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      #最大连接等待超时时间
      max-wait: 60000
      initial-size: 1
      max-active: 100
# 内置tomcat端口号
server:
  port: 8082

# micro job node 配置
hengboy:
  job:
    node:
      # server端口号，默认：9999
      reg-port: 9090
